[versions]
minecraft = "1.17.1"
yarn = "1.17.1+build.31"

fabric-loader = "0.11.6"
fabric-api = "0.37.1+1.17"

sgui = "1.0.0-rc4+1.17.1"
polymer = "0.1.0-rc.6+1.17.1"

server-translations-api = "1.4.5+1.17"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

sgui = { module = "eu.pb4:sgui", version.ref = "sgui" }
polymer = { module = "eu.pb4:polymer", version.ref = "polymer" }

server-translations-api = { module = "fr.catcore:server-translations-api", version.ref = "server-translations-api" }
